name: Proclnas Blog
description: Writing about code, psychology and the psychedelic mind process...
meta_description: "Writing about code, psychology and the psychedelic mind process"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: 'https://proclnas.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://proclnas.github.io'
author:
  name: 'Proclnas'
  email: 'proclnas@gmail.com'
  github: 'proclnas'
  twitter: 'proclnas'

