title: Proclnas Blog
description: Writing about code, psychology and the psychedelic mind process...
baseurl: /
url: 'https://proclnas.github.io'

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: proclnas
email: proclnas@gmail.com

navigation:
  - text: Home
    url: /
  - text: Docs
    url: /docs

projects:
  - name: git-secret
    description: A bash-tool to store your private data inside a git repository.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true

social:
  - service: github
    username: proclnas
    link: https://github.com/proclnas
  - service: twitter
    username: proclnas
    link: https://twitter.com/proclnas

# Plugins
gems:
  - jekyll-seo-tag
